name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master # Твоя головна гілка

permissions:
  contents: write # Дозвіл на оновлення гілки gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        # Збираємо проект для продакшну
        run: npm run build -- --configuration=production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # ВАЖЛИВО: Перевір назву проекту в package.json. 
          # Зазвичай шлях: dist/назва-проекту/browser
          folder: dist/monte-cristo-hotel/browser 
          branch: gh-pages
          # Твій домен
          cname: monte-kristo.itkamianets.com